

demo-instance.us-central1-a.c.independent-way-410316.internal
*** Found local files:
***   * /home/vishprospero/airflow/logs/dag_id=excel_to_csv_pyspark/run_id=manual__2024-06-01T03:11:47.848481+00:00/task_id=convert_excel_to_csv/attempt=2.log
[2024-06-01, 03:17:01 UTC] {local_task_job_runner.py:120} ▼ Pre task execution logs
[2024-06-01, 03:17:01 UTC] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: excel_to_csv_pyspark.convert_excel_to_csv manual__2024-06-01T03:11:47.848481+00:00 [queued]>
[2024-06-01, 03:17:01 UTC] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: excel_to_csv_pyspark.convert_excel_to_csv manual__2024-06-01T03:11:47.848481+00:00 [queued]>
[2024-06-01, 03:17:01 UTC] {taskinstance.py:2306} INFO - Starting attempt 2 of 2
[2024-06-01, 03:17:01 UTC] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): convert_excel_to_csv> on 2024-06-01 03:11:47.848481+00:00
[2024-06-01, 03:17:01 UTC] {standard_task_runner.py:63} INFO - Started process 4891 to run task
[2024-06-01, 03:17:01 UTC] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'excel_to_csv_pyspark', 'convert_excel_to_csv', 'manual__2024-06-01T03:11:47.848481+00:00', '--job-id', '83', '--raw', '--subdir', 'DAGS_FOLDER/pyspark_excel_to_csv.py', '--cfg-path', '/tmp/tmp4wspnng9']
[2024-06-01, 03:17:01 UTC] {standard_task_runner.py:91} INFO - Job 83: Subtask convert_excel_to_csv
[2024-06-01, 03:17:01 UTC] {task_command.py:426} INFO - Running <TaskInstance: excel_to_csv_pyspark.convert_excel_to_csv manual__2024-06-01T03:11:47.848481+00:00 [running]> on host demo-instance.us-central1-a.c.independent-way-410316.internal
[2024-06-01, 03:17:01 UTC] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='excel_to_csv_pyspark' AIRFLOW_CTX_TASK_ID='convert_excel_to_csv' AIRFLOW_CTX_EXECUTION_DATE='2024-06-01T03:11:47.848481+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-06-01T03:11:47.848481+00:00'
[2024-06-01, 03:17:01 UTC] {taskinstance.py:430} ▲▲▲ Log group end
[2024-06-01, 03:17:01 UTC] {taskinstance.py:441} ▼ Post task execution logs
[2024-06-01, 03:17:01 UTC] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/vishprospero/miniconda3/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/vishprospero/miniconda3/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/vishprospero/miniconda3/lib/python3.11/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/vishprospero/miniconda3/lib/python3.11/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/vishprospero/miniconda3/lib/python3.11/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/vishprospero/airflow/dags/pyspark_excel_to_csv.py", line 55, in convert_excel_to_csv
    spark = create_spark_session()
            ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/vishprospero/airflow/dags/pyspark_excel_to_csv.py", line 37, in create_spark_session
    .getOrCreate()
     ^^^^^^^^^^^^^
  File "/home/vishprospero/miniconda3/lib/python3.11/site-packages/pyspark/sql/session.py", line 497, in getOrCreate
    sc = SparkContext.getOrCreate(sparkConf)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/vishprospero/miniconda3/lib/python3.11/site-packages/pyspark/context.py", line 515, in getOrCreate
    SparkContext(conf=conf or SparkConf())
  File "/home/vishprospero/miniconda3/lib/python3.11/site-packages/pyspark/context.py", line 201, in __init__
    SparkContext._ensure_initialized(self, gateway=gateway, conf=conf)
  File "/home/vishprospero/miniconda3/lib/python3.11/site-packages/pyspark/context.py", line 436, in _ensure_initialized
    SparkContext._gateway = gateway or launch_gateway(conf)
                                       ^^^^^^^^^^^^^^^^^^^^
  File "/home/vishprospero/miniconda3/lib/python3.11/site-packages/pyspark/java_gateway.py", line 97, in launch_gateway
    proc = Popen(command, **popen_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/vishprospero/miniconda3/lib/python3.11/subprocess.py", line 1026, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/home/vishprospero/miniconda3/lib/python3.11/subprocess.py", line 1950, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: '/home/vishprospero/.ivy2/cache/com.crealytics/spark-excel_2.12/./bin/spark-submit'
[2024-06-01, 03:17:01 UTC] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=excel_to_csv_pyspark, task_id=convert_excel_to_csv, run_id=manual__2024-06-01T03:11:47.848481+00:00, execution_date=20240601T031147, start_date=20240601T031701, end_date=20240601T031701
[2024-06-01, 03:17:01 UTC] {standard_task_runner.py:110} ERROR - Failed to execute job 83 for task convert_excel_to_csv ([Errno 2] No such file or directory: '/home/vishprospero/.ivy2/cache/com.crealytics/spark-excel_2.12/./bin/spark-submit'; 4891)
[2024-06-01, 03:17:01 UTC] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-06-01, 03:17:01 UTC] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-06-01, 03:17:01 UTC] {local_task_job_runner.py:222} ▲▲▲ Log group end